% clear, clc;
% p = 0.95:0.01:1.05;
% p = p*0.1;
% p1 = (1 - p)/3;
% p2 = (1 - p);
% max_money = zeros(1, 11);
% mean_money= zeros(1, 11);
% completion= zeros(1, 11);
% harvest= zeros(1, 11);
% for i = 1:length(p)
%     [max_money(i), mean_money(i), completion(i), harvest(i)] = p4sensity(p1(i),p2(i));
% end
subplot(2,1,1);
set(gca,'FontSize',10);
hold on;
plot(completion);
scatter(1:length(completion), completion, 'r*');
ylim([0.8,1]);
ylabel("通关比例");
xlabel("沙暴概率");
xticks(1:length(harvest));
xticklabels(p);
hold off;
% subplot(4,1,2);
% set(gca,'FontSize',10);
% hold on;
% plot(harvest);
% scatter(1:length(harvest), harvest, 'r*');
% ylim([0,0.2]);
% ylabel("赚钱的人的比例");
% xlabel("沙暴概率");
% xticks(1:length(harvest));
% xticklabels(p);
% hold off;
% subplot(4,1,3);
% set(gca,'FontSize',10);
% hold on;
% plot(max_money);
% scatter(1:length(max_money), max_money, 'r*');
% ylim([15000,20000]);
% ylabel("最多资金/元");
% xlabel("沙暴概率");
% xticks(1:length(harvest));
% xticklabels(p);
% hold off;
subplot(2,1,2);
set(gca,'FontSize',10);
hold on;
plot(mean_money);
scatter(1:length(mean_money), mean_money, 'r*');
ylim([5000,10000]);
ylabel("资金均值/元");
xlabel("沙暴概率");
xticks(1:length(harvest));
xticklabels(p);
hold off;